### ISSUE TITLE
Aztec Code

### ISSUE THREAD

**Issue by ruudk** [boombuler/barcode#10]
Would be nice to have support for Aztec Code too (https://en.wikipedia.org/wiki/Aztec_Code)

**Comment by willtrking** [comment]
+1

**Comment by boombuler** [comment]
Hi, I would love to implement it but I dont have all required information to so so :(

**Comment by ruudk** [comment]
For me it is solved by using Mint (binary) to generate the Aztec barcode. Not as nice as doing it in Go but my knowledge of Go is not good enough to port an existing Aztec encoder to it.

**Comment by boombuler** [comment]
I've started porting the aztec code generation from zxing. 
I would normally not do this because I started this project to learn how different barcodes are encoded from scratch. 
But I guess its better to learn from other peoples code, then not learning anything :)

**Comment by ruudk** [comment]
Cool! I would definitely switch to using Aztec generation through go lang!

I learned a lot by porting PDF417 barcodes from PHP to Go :)

**Comment by boombuler** [comment]
Hey, please test this and let me know if there are any issues...

**Comment by willtrking** [comment]
Seems working for my use case (encoding 2 space-padded int64 seperated with a dash). This is much appreciated!!
