### ISSUE TITLE
144x144 datamatrix are not possible

### ISSUE THREAD

**Issue by sammyf** [boombuler/barcode#11]
When trying to create a datamatrix from a long text which would result in a 144x144 grid, the code crashes with an index out of range runtime error in 
/barcode_master/src/github.com/boombuler/barcode/datamatrix/errorcorrection.go:69

As far as I can tell from the datamatrix specs, this type of grid has alternating block size and CWs.

**Comment by boombuler** [comment]
Indeed it seems that this one is an exception and needs a different error correction size for some of the blocks... I will have a look at it.

**Comment by sammyf** [comment]
Hey there. Thanks for the fast response. 
The encoder doesn't crash anymore, but the datamatrix seems to be invalid (tested on https://zxing.org/w/decode.jspx and http://boy.co.ua/decode.php :/

**Comment by boombuler** [comment]
I've just tested some other generators, seems like the pages you have used for testing have some problems with those 144x144 barcodes...

But I'm glad it works now :)
