### ISSUE TITLE
QR: 1 dot sized framed for easer scanning

### ISSUE THREAD

**Issue by dawidp** [boombuler/barcode#21]
It would be nice to have a white frame around the QR code for easier scanning as not all scanners can scan this code if placed on dark background.

**Comment by dawidp** [comment]
OK, after deleting and generating the image again it has the white frame. I don't know why it didn't have at the first time. This could be cause by my local hardware fluctuations...

**Comment by boombuler** [comment]
You could use a simple helper like this:

```golang
type WhiteBorder struct {
	width   int
	barcode barcode.Barcode
}

func (wb WhiteBorder) At(x, y int) color.Color {
	bounds := wb.barcode.Bounds()
	w := bounds.Dx()
	h := bounds.Dy()
	if x < wb.width || x >= w+wb.width || y < wb.width || y >= h+wb.width {
		return color.White
	}
	return wb.barcode.At(x-wb.width, y-wb.width)
}

func (wb WhiteBorder) Bounds() image.Rectangle {
	b := wb.barcode.Bounds()
	return image.Rect(0, 0, b.Dx()+2*wb.width, b.Dy()+2*wb.width)
}

func (wb WhiteBorder) ColorModel() color.Model {
	return wb.barcode.ColorModel()
}

func Main() {
  bc, _ := qr.Encode("Foobar", qr.L, qr.Auto)

  var img image.Image = WhiteBorder{10, bc}

  png.Encode(file, img)
}
```

**Comment by boombuler** [comment]
Btw to explain why you didn't have a white border on the first try:
I guess you used a scaled barcode?

The scaling function is very simple. It only calculates a integer scale factor (for example *3) and fills the rest with white pixels.

So if you want to ensure the white border use the code above.
