### ISSUE TITLE
[Question] Genrating an GS1-128 barcode

### ISSUE THREAD

**Issue by nilpath** [boombuler/barcode#23]
Hi!

We're using you library to generate barcodes and so far it been working geat. 

However we've hit a road bump in generating a GS1-128 barcode (most likely we've missunderstood how the library works) when it comes to the hidden FNC1 character. Looking though the source it looks like you support this but it's a bit unclear to us how should generate this type of label.

Are we supposed to send in the FNC1 character manually?

**Comment by boombuler** [comment]
yes indeed. you need to add the FNC1 by hand since it can encode all kind of Code-128 barcodes and not just GS1 compatible. 

There is a constant `code128.FNC1` which you will need to put in front of your string.

If you need any help please let me know.

**Comment by nilpath** [comment]
tank you,  the FNC1 seem to work great however, we're trying to get this barcodes validated/certified by an external source and it seem like they expected FNC1 to be inserted before `AI 96` whatever that means.

do you have an idea what that could mean? appreciate the help 👍

**Comment by nilpath** [comment]
hm noticed now that it probably implementation specific. something unrelated to the actuall barcode generation.

thanks for the help otherwise 👍

**Comment by boombuler** [comment]
I've just read some docs about GS-1 and it seems like it needs a FNC1 to terminate each `AI` that has variable length. But I'm not totally sure about it.

for example: `(30)19(21)123456789012` needs to be `<FNC1>3019<FNC1>21123456789012`

**Comment by nilpath** [comment]
@boombuler yes thats our conclusion as well :)
