### ISSUE TITLE
Can I have content string under the barcode

### ISSUE THREAD

**Issue by charleswklau** [boombuler/barcode#33]
Surely, it is for 1D barcode.
I used Code128 to generate my barcode, and used Scale to have my expected size.
But is there a way place the content string under the barcode? 
something like this, https://en.wikipedia.org/wiki/Barcode#/media/File:Code_128B-2009-06-02.svg

**Comment by boombuler** [comment]
Hi,

I have created a wiki page with some sample code for you:
https://github.com/boombuler/barcode/wiki/Content-String

Due to the complex topic of font rendering I will not include it to this lib but you should be able to get it working with the sample code from the wiki.
