### ISSUE TITLE
QR: transparent

### ISSUE THREAD

**Issue by accaolei** [boombuler/barcode#36]
How to set the background color to be transparent?
How do you set the size of the border?

**Comment by boombuler** [comment]
Hi, please have a look at the wiki pages for [Colorized-barcode](https://github.com/boombuler/barcode/wiki/Colorized-barcode) and [Quiet-Zones](https://github.com/boombuler/barcode/wiki/Quiet-Zones)

**Comment by accaolei** [comment]
Thinks
