### ISSUE TITLE
Printer and reader

### ISSUE THREAD

**Issue by gedw99** [boombuler/barcode#38]
This library looks just like what I need.

I am planning to integrate it with a USB based bar code reader. Has anyone tried this yet ?

Also reading via the camera on a phone.
I can give it a go and submit a sample but wanted to check first it will be accepted ?

**Comment by boombuler** [comment]
I would accept such code if you are willing to maintain ist too.

**Comment by gedw99** [comment]
Can't promise. When I have done the integration I will put it on my GitHub and you can link to it in the readme. Sounds good ?

**Comment by boombuler** [comment]
I'm fine with that :)

gedw99 <notifications@github.com> schrieb am Mo., 26. März 2018, 13:53:

**Comment by boombuler** [comment]
@gedw99 any update on this?

**Comment by gedw99** [comment]
Nah just too much to do.

But I am sure it's very easy...
Printing is just a matter of using the pdf and printing plugin. It's on the dart pub website and works well.

https://github.com/DavBfr/dart_pdf

Reading the camera and checking if it's a barcode should be easy by also checking for a plugin. 

Sorry I don't have time but it's not on my critical path. But I really think using other plugins makes it pretty easy.

If you get stuck holler ...
