### ISSUE TITLE
Supporting barcode text underneath code 128

### ISSUE THREAD

**Issue by huttotw** [boombuler/barcode#43]
Normally, code 128 barcodes have the barcode text underneath them.

![barcode](https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Barcode_diagram.svg/400px-Barcode_diagram.svg.png)

Is there any plan to support this? If so, at a high level what is involved?

I may purpose a solution similar to `scaledBarcode`, but `writtenBarcode`, that places the encoded text below the barcode, but in the image.

**Comment by boombuler** [comment]
Hi, pleased have a Look at https://github.com/boombuler/barcode/wiki/Content-String

**Comment by boombuler** [comment]
Due to the complex topic of font rendering I will not include it to this lib but you should be able to get it working with the sample code from the wiki.

Let me know if you need further help

**Comment by huttotw** [comment]
@boombuler thank you, that was exactly what I needed.
