### ISSUE TITLE
base64 png

### ISSUE THREAD

**Issue by flrnt** [boombuler/barcode#45]
Is there a way to directly encode the barcode to base64 ? Then I could output into pdf as img tag

**Comment by boombuler** [comment]
Hi,

if you want a base64 encoded png, you could simply combine the png encoder + bytes.buffer like this:

```golang
package main

import (
  "github.com/boombuler/barcode/qr"
  "bytes"
  "image/png"
  "encoding/base64"
  "fmt"
)

func main() {
    bc, _ := qr.Encode("Foobar", qr.M, qr.Auto)
    buf := new(bytes.Buffer)
    base := base64.NewEncoder(base64.StdEncoding, buf)
    png.Encode(base, bc)
    base.Close()
    fmt.Println(buf.String())
}

```

Hope this helps?

**Comment by flrnt** [comment]
Thank you @boombuler, I'm pretty close to this. Now i'm stuck into another problem. I generated barcode (128), converted it to base64. When I pass it to my template like so : `<img src="{{ .base64BarcodeUrl }}">` it breaks my png once I open the pdf. But if I take the content of base64BarcodeUrl and paste it directly as src to my img tag, it works like a charm. 
`base64BarcodeUrl = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAABkEAAAAABJ+o5fAAABYUlEQVR4nOzSUYrCMBRA0ekw+99yhyLBUhIq2Pt3zo9V40si92/ffx6zba/XY+bxPGaPz8d317Xj/fksq9/P5p/Xr+Ze18/OtZoxO+/svqs51z1W97j7n+6eZ/vMzvvJfb/1+9woeBMWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGREBYJYZEQFglhkRAWCWGR+A8AAP//9bRAyVZD8C0AAAAASUVORK5C"`
Is there any issue I'm not aware about "injecting" some data ?
