### ISSUE TITLE
cannot assign barcode.Barcode to img (type barcode.BarcodeIntCS) in multiple assignment:

### ISSUE THREAD

**Issue by Symbianl** [boombuler/barcode#47]
cannot assign barcode.Barcode to img (type barcode.BarcodeIntCS) in multiple assignment:
        barcode.Barcode does not implement barcode.BarcodeIntCS (missing CheckSum method)

**Comment by Symbianl** [comment]
How to deal with it？

**Comment by boombuler** [comment]
Hi,

i guess ist the same problem as it was in this PR https://github.com/boombuler/barcode/pull/42

Kind regards
