### ISSUE TITLE
Can I take parameters after the url?

### ISSUE THREAD

**Issue by gongpulin** [boombuler/barcode#48]
qrCode, _ := qr.Encode('http://www.aa.com?a=123', qr.M, qr.Auto)

Scan the QR code and open it with a browser. The request address becomes https://www.aa.com/?a=123

**Comment by gongpulin** [comment]
qrCode, _ := qr.Encode('http://www.aa.com?a=123', qr.M, qr.Auto)

Scan the QR code and open it with a browser. The request address becomes https://www.aa.com/?a=123

**Comment by gongpulin** [comment]
qrCode, _ := qr.Encode('http://www.aa.com?a=123', qr.M, qr.Auto)

Scan the QR code and open it with a browser. The request address becomes https://www.aa.com/?a=123

Why is the question mark preceded by a slash and http becomes https?

I look forward to hearing from you.

**Comment by boombuler** [comment]
Hi,

the barcode lib does not any kind of string processing. so the text is correctly encoded. I guess the reader does some post-processing since your text is not a valid url.

Kind regards.

**Comment by RobertGrantEllis** [comment]
Here is why:

```shell
$ curl -I http://www.aa.com?a=123
HTTP/1.1 301 Moved Permanently
Server: AkamaiGHost
Content-Length: 0
Location: https://www.aa.com/?a=123
Date: Mon, 19 Nov 2018 19:34:59 GMT
Connection: keep-alive
Set-Cookie: aka_cr_code=US-; path=/; secure
X-Frame-Options: SAMEORIGIN
Set-Cookie: akavpau_www_aafullsite=1542656399~id=0451c2a4a5f8cc33e5dd3da2eab0746a; Path=/
```
