### ISSUE TITLE
QR encode broken for L correction level

### ISSUE THREAD

**Issue by divan** [boombuler/barcode#5]
Hi, I've catched encoding bug with QR encoded with L error correction level. Data read by scanner has one byte different from original. Data is in base64, and code.Content() returns correct value, so error must be somewhere in rendering.

I don't know QR algorithm internals well, and it could be possible that I simply have to increase error correction level, but I doubt it.

Here is an example code with real value from production:
http://play.golang.org/p/IWmXxzQzT3 (it will not work in playground, must be run locally)

**Comment by boombuler** [comment]
I can reproduce the issue and will have a look... But may take a few days.

**Comment by divan** [comment]
No problem, I've currently switched to another library, so no hurry for me.
Thanks!

**Comment by boombuler** [comment]
Weird thing is this side: http://www.pclviewer.com/rs2/calculator.html calculates the same error correction as my code :-(

**Comment by divan** [comment]
If it helps, this code for ReedSolomon seems to be correct:
https://code.google.com/p/go-qrcode/source/browse/#git%2Freedsolomon

**Comment by boombuler** [comment]
still no idea what was wrong with the old code but I rewrote the error correction calculation with something that is more close to the zxing code.
