### ISSUE TITLE
UUID

### ISSUE THREAD

**Issue by ivanjaros** [boombuler/barcode#50]
Hi, I am trying to use uuid for barcode but every online validator shows resulting image as invalid.
[This generator](https://barcode.tec-it.com/en/Code128?data=cd171f7c-560d-4a62-8d65-16b87419a58c) produces valid uuid barcode according to [this validator](https://online-barcode-reader.inliteresearch.com/).

From what I've gathered it has most likely something to do with the FNC1 character but I have no idea what. I tried to prefix the uuid with it but no success.

**Comment by boombuler** [comment]
Hi, could you give me some code? Then I might be able to help you

**Comment by boombuler** [comment]
this might be related: https://github.com/boombuler/barcode/issues/23

**Comment by ivanjaros** [comment]
I saw the #23 but I didn't understand what the solution was supposed to be.

This is my code right now, nothing special, mostly pieces of code you referenced in different issues.

```
package uuidbc

import (
	"bytes"
	"encoding/base64"
	"github.com/boombuler/barcode"
	"github.com/boombuler/barcode/code128"
	"golang.org/x/image/font"
	"golang.org/x/image/font/basicfont"
	"golang.org/x/image/math/fixed"
	"image"
	"image/color"
	"image/draw"
	"image/png"
)

func subtitleBarcode(bc barcode.Barcode) image.Image {
	fontFace := basicfont.Face7x13
	fontColor := color.RGBA{0, 0, 0, 255}
	margin := 5 // Space between barcode and text

	// Get the bounds of the string
	bounds, _ := font.BoundString(fontFace, bc.Content())

	widthTxt := int((bounds.Max.X - bounds.Min.X) / 64)
	heightTxt := int((bounds.Max.Y - bounds.Min.Y) / 64)

	// calc width and height
	width := widthTxt
	if bc.Bounds().Dx() > width {
		width = bc.Bounds().Dx()
	}
	height := heightTxt + bc.Bounds().Dy() + margin

	// create result img
	img := image.NewRGBA(image.Rect(0, 0, width, height))
	// draw the barcode
	draw.Draw(img, image.Rect(0, 0, bc.Bounds().Dx(), bc.Bounds().Dy()), bc, bc.Bounds().Min, draw.Over)

	// TextPt
	offsetY := bc.Bounds().Dy() + margin - int(bounds.Min.Y/64)
	offsetX := (width - widthTxt) / 2

	point := fixed.Point26_6{
		X: fixed.Int26_6(offsetX * 64),
		Y: fixed.Int26_6(offsetY * 64),
	}

	d := &font.Drawer{
		Dst:  img,
		Src:  image.NewUniform(fontColor),
		Face: fontFace,
		Dot:  point,
	}
	d.DrawString(bc.Content())
	return img
}

func Encode(uuid string) (b64image string, err error) {
	bc, err := code128.EncodeWithoutChecksum(string(append([]rune{code128.FNC1}, []rune(uuid)...)))
	if err != nil {
		return "", err
	}

	scaled, err := barcode.Scale(bc, bc.Bounds().Dx(), 100)
	if err != nil {
		return "", err
	}

	img := subtitleBarcode(scaled)

	buf := bytes.NewBuffer(nil)
	base := base64.NewEncoder(base64.StdEncoding, buf)
	if err := png.Encode(base, img); err != nil {
		return "", err
	}

	return "data:image/png;base64,"+buf.String(), base.Close()
}
```

My goal is to be able to use uuid v4(or other type of long alnum id) to label items in a warehouse and handheld scanners to be able to properly scan them.

I found this solution https://stackoverflow.com/a/31706056 that transforms the uuid into decimal number, but I was not able to do that so I kept the uuid as is for now.

**Comment by boombuler** [comment]
Both validators work fine if I include the checksum and don't provide the fnc1 character. 

I used this code:
```golang
package main

import (
	"image"
	"image/png"
	"os"

	"github.com/boombuler/barcode"
	"github.com/boombuler/barcode/code128"
)

func Encode(uuid string) (img image.Image, err error) {
	bc, err := code128.Encode(uuid)
	if err != nil {
		return nil, err
	}

	scaled, err := barcode.Scale(bc, bc.Bounds().Dx(), 100)
	if err != nil {
		return nil, err
	}

	return scaled, nil
}

func main() {
	bc, _ := Encode("78e2ca78-b9e0-4465-8c73-a6c7ed039b23")
	f, _ := os.Create("bc.png")
	defer f.Close()

	png.Encode(f, bc)
}
```

So it seems those decoders don't decode GS-1 but just simple Code128 codes.

**Comment by ivanjaros** [comment]
I tried it and it works. I guess the issue was in that I have used online base64 image "generator", instead of creating images locally since I was working with those base64 strings.

**Comment by boombuler** [comment]
That should make no difference. I think its the missing checksum
