### ISSUE TITLE
How to realize the two-dimensional code of art

### ISSUE THREAD

**Issue by fenglijunnb** [boombuler/barcode#61]
Not the black and white qr codes that we have now

**Comment by boombuler** [comment]
I'm not exactly sure what you mean, but if you just want to change the colors, have a look at the wiki:
https://github.com/boombuler/barcode/wiki/Colorized-barcode

**Comment by fenglijunnb** [comment]
No, no, not changing the color, but changing the shape of the qr code
![it399 com qrcode2](https://user-images.githubusercontent.com/48191768/77293464-583b9380-6d1d-11ea-90ec-beca620c70d9.jpg)
Something like that

**Comment by boombuler** [comment]
Doing something like this would require a little more coding then just using this library. You could generate the barcode, but if you want to add such artistic effects you have to get creative yourself. 
Sorry for that

**Comment by fenglijunnb** [comment]
I think you can try to try art two-dimensional code, after all, black and white will be eliminated, I hope you can listen to my opinion

**Comment by boombuler** [comment]
Such kind of things can be achieved by using tilesets and a little tinkering, it should not be very complicated, just pick a random tile from the set and do some floodfilling with the data from the barcode. This kind of stuff is very specific to your problem and should imho not be included in a general barcode lib. Its just a few lines of code if you know exactly what you want but much more code if you try to generalize it.

**Comment by fenglijunnb** [comment]
So if you implement the following two-dimensional code, how will you operate, can you implement an example
![it399 com qrcode2](https://user-images.githubusercontent.com/48191768/77395965-b3cd5600-6ddd-11ea-8a9e-0965ac98b8eb.jpg)
In fact, its location is radian, and not black and white, we can give the two-dimensional code more style

**Comment by fenglijunnb** [comment]
If this is the complexity of the picture, then we can also achieve this

![image](https://user-images.githubusercontent.com/48191768/77396231-5259b700-6dde-11ea-83ac-7206b92210d0.png)

![image](https://user-images.githubusercontent.com/48191768/77396206-42da6e00-6dde-11ea-85bb-594ea61b493d.png)

**Comment by boombuler** [comment]
Looks like you already have a service to do this kind of barcodes?!? So why do you want a library which is used to generate the barcode data to create fancy images? That should be a job of a fancy drawing lib. At least the last one is so easy that anyone who just googles for about 2 minutes should be able to create such an image... just walk the barcode from this library pixel by pixel, if its a black one, draw a circle, otherwise do nothing...

**Comment by fenglijunnb** [comment]
No, no, I got this service through the website, he needs money, if I want a lot, I need more money, in order to reduce unnecessary expenditure, so I need to ask you how to operate

**Comment by huysentruitw** [comment]
The 3 examples here can be perfectly generated using this library or my .NET port at https://github.com/huysentruitw/barcoder

Your first example is just an image wrapped around the original QR code in the center. The last two examples just use a different style of rendering the square dots.

You can make all based on the 2-dimensional data you get from the [qrcode class](https://github.com/boombuler/barcode/blob/master/qr/qrcode.go).

The special kind of rendering you're requesting is outside the scope of this library (and my port). Also, there is a reason why that service is requiring money for their work. The free labor we do as open-source developers is limited.

**Comment by fenglijunnb** [comment]
@huysentruitw Pardon my stupidity.You really don't see your code.And it is not the code of go, so I really can't take your advice, but I hope you can provide a style qr code of go
