### ISSUE TITLE
Unreadable code128 image

### ISSUE THREAD

**Issue by vladkras** [boombuler/barcode#68]
I use this code to generate image

```
code, err := code128.EncodeWithoutChecksum("1234567890")
...
code, err = barcode.Scale(code, 180, 90)
...
err = png.Encode(w, code)
```
(some lines are skipped)
this is what I got in browser
![image](https://user-images.githubusercontent.com/3240317/127965227-c02aa93e-83c8-4857-aeef-b299789f1911.png)
![image](https://user-images.githubusercontent.com/3240317/127965083-8bf8d360-4f16-4268-89f7-e3fb4a4cf789.png)
and the lower image was generated with web online generator. As you can see there is difference starting from line 19, which makes my barcode incorrect. I tried two different mobile scanners, both of them easily scan lower image but cannot recognize upper one.

Do you have the same barcode for `1234567890`?

**Comment by vladkras** [comment]
UPD: also I tried to save it to file as written in README just to exclude browser problems - some crop or resize problem, and this doesn't work too. I can't scan generated image:
![image](https://user-images.githubusercontent.com/3240317/127967896-d3fbad27-a855-4975-92eb-96c3acfeeb3d.png)

**Comment by boombuler** [comment]
Try to use `Encode` instead of `EncodeWithoutChecksum`. That results to the same image as the online generator...

```golang

func main() {
	var code barcode.Barcode
	code, _ = code128.Encode("1234567890")
	code, _ = barcode.Scale(code, 180, 90)
	
	file, _ := os.Create("code.png")
	defer file.Close()

	png.Encode(file, code)
}

```

**Comment by vladkras** [comment]
Yes, this works, thanks. But isn't it wierd that this functions work differently?

**Comment by boombuler** [comment]
It works as intended. The Encode is the default way to create barcodes, the Encode**WithoutChecksum** function was added later to solve https://github.com/boombuler/barcode/issues/16

**Comment by vladkras** [comment]
ok, I see, but shouldn't it be mentioned in godoc?

"without check sum" doesn't look like "encodes differently", but like "returns less values"
