### ISSUE TITLE
code128 is broken?

### ISSUE THREAD

**Issue by moshemarciano** [boombuler/barcode#74]
I am doing

```go
	barCode, err := code128.Encode(content)
	barCode, err = barcode.Scale(barCode, size, size/2)
```

and getting

```
./main.go:130:17: cannot use barcode.Scale(barCode, size, size / 2) (value of type barcode.Barcode) as type barcode.BarcodeIntCS in assignment:
        barcode.Barcode does not implement barcode.BarcodeIntCS (missing CheckSum method)
```

if I use the Encode with not scaling and try

```go
	png.Encode(w, barCode)
```

I will get a 1px height barcode that is unusable

if I use the EncodeWithoutChecksum method, it does work, and allows me to scale, but the codes can't be read by any iOS barcode scanner

**Comment by boombuler** [comment]
Hi,

no it works fine. The problem is that code128.Encode returns a `BarcodeIntCS` while the `Scale` function returns a `Barcode` so if you explicitly declare the `barCode` variable it should work fine:

```golang
var barcode barcode.Barcode
var error Error
barcode, err = code128.Encode(content)
barcode, err = barcode.Scale(barcode, size, size/2)
```

or something similar should do the trick...

**Comment by moshemarciano** [comment]
yes it does work, thank you for the prompt response
