### ISSUE TITLE
PDF417 support

### ISSUE THREAD

**Issue by ruudk** [boombuler/barcode#9]
Would by really nice to have support for https://en.wikipedia.org/wiki/PDF417

**Comment by boombuler** [comment]
Hi,

I will not have much time the next weeks but if anyone wants to start with this:
http://grandzebu.net/informatique/codbar-en/pdf417.htm
Should contain most of the needed information to create an pdf417 encoder.

**Comment by ruudk** [comment]
I'm currently working on a port of https://github.com/ihabunek/pdf417-php to Golang :)

**Comment by ruudk** [comment]
Implemented in https://github.com/ruudk/golang-pdf417

**Comment by boombuler** [comment]
@ruudk 
I'm thinking of merging your code to this repo. Is that ok with you?
